version: '3.9'

volumes:
  postgres_data:
    driver: local
    
services:
  postgres:
    image: postgres
    volumes:
      - ./keycloak/postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pass
      # need to set PGDATA to a sub-directory to fix "invisible file error" in mount point
      PGDATA: /var/lib/postgresql/data/pgdata/
    secrets:
      - postgres_pass
    networks:
      secure_network:
        ipv4_address: 10.5.0.3

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: 10.5.0.3
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD_FILE: /run/secrets/postgres_pass
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD_FILE: /run/secrets/keycloak_pass
    secrets:
      - keycloak_pass
      - postgres_pass
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      secure_network:
        ipv4_address: 10.5.0.4
        
  ca_authenticator:
    build: 
      context: .
      dockerfile: ./Dockerfile
      network: host
    image: ca_authenticator
    volumes:
      - ./volume/:/usr/src/app/volume/
    ports:
      - "5001:5001"
    secrets:
      - ca_auth_env
    networks:
      secure_network:
        ipv4_address: 10.5.0.5

secrets:
  keycloak_pass:
    file: secrets/keycloak_pass.txt
  postgres_pass:
    file: secrets/postgres_pass.txt
  ca_auth_env:
    file: secrets/ca_auth.env

networks:
  secure_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.1
