version: '3'

volumes:
  postgres_data:
    driver: local
    
services:
  mongodb:
    image : mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb/data/db/:/data/db/
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      secure_network:
        ipv4_address: 10.5.0.2
 
  postgres:
    image: postgres
    volumes:
      - ./keycloak/postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      # need to set PGDATA to a sub-directory to fix "invisible file error" in mount point
      PGDATA: /var/lib/postgresql/data/pgdata/
    networks:
      secure_network:
        ipv4_address: 10.5.0.3

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: 10.5.0.3
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres
    networks:
      secure_network:
        ipv4_address: 10.5.0.4
        
  ca_authenticator:
    build: 
      context: .
      dockerfile: ./Dockerfile
      network: host
    image: ca_authenticator
    volumes:
      - ./volume/:/usr/src/app/volume/
    ports:
      - "5001:5001"
    environment:
      CAPass: prova
      serverPass: prova
    depends_on:
      - keycloak
    networks:
      secure_network:
        ipv4_address: 10.5.0.5
      
networks:
  secure_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.1      